disabled_rules:
- trailing_whitespace
- cyclomatic_complexity
opt_in_rules:
- empty_count
- empty_string
- force_unwrapping
excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib
line_length:
    warning: 200
    error: 300
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 30
    error: 60
function_parameter_count:
    warning: 5
    error: 7

file_length:
    warning: 200
    error: 300
    ignore_comment_only_lines: true

   
force_unwrapping:
  severity: error # explicitly
force_cast: error # implicitly
force_try:
  severity: error # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
# they can set both implicitly with an array
type_body_length:
    warning: 200
    error: 300
    ignore_comment_only_lines: true
# or they can set both explicitly

# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 3 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
identifier_name:
  min_length: # only min_length
    error: 3 # only error
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
    - sut
    - to
reporter: "xcode"
